### ISSUE TITLE
[Server] Flaky test 

### ISSUE THREAD

**Issue by bmansoob** [Shopify/app_profiler#96]
I was looking at the flaky test here https://github.com/Shopify/app_profiler/actions/runs/6561028589/attempts/1 and was able to see (via printf debuging) that the finaliser is getting called mid test. https://github.com/Shopify/app_profiler/blob/329d2922298467b77e302b22b951bb02fddabd65/lib/app_profiler/server.rb#L220.

I was able to reliably reproduce [this](https://github.com/Shopify/app_profiler/compare/flaky-test-reproduce?expand=1) by forcing a GC run. Looking at this https://ruby-doc.org/core-3.0.1/ObjectSpace.html#method-c-define_finalizer though, the finaliser should not run on GC?

>Note that if your finalizer references the object to be finalized it will never be run on [GC](https://ruby-doc.org/core-3.0.1/GC.html), although it will still be run at exit. You will get a warning if you capture the object to be finalized as the receiver of the finalizer.

Thoughts @byroot?

**Comment by casperisfine** [comment]
> the finaliser should not run on GC?

Why not? If the object on which the finalizer was set is garbage collected, the finalizer will be called during the sweeping phase (at the end of GC).

**Comment by casperisfine** [comment]
I think https://github.com/Shopify/app_profiler/pull/97 would work.
